/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        clash: ["var(--font-clash),'sans-serif'"],
        brico: ["var(--font-brico),'sans-serif'"],
      },
      colors: {
        backgroundColor: "hsla(210, 7%, 12%, 1);",
        cardbgGray: "hsla(216, 6%, 15%, 1)",
        radiusBgGray: "hsla(210, 7%, 22%, 1)",
        titleGray: "hsla(210, 7%, 42%, 1)",
        textGray: "hsla(210, 7%, 52%, 1)",
        footerDateTitle: "hsla(210, 7%, 62%, 1)",
        textWhite: "hsla(200, 7%, 82%, 1)",
        titleWhite: "hsla(200, 7%, 92%, 1);",
      },
      keyframes: {
        "pulse-dot": {
          "0%": { transform: "scale(0.9)" },
          "50%": { transform: "scale(1)" },
          "100%": { transform: "scale(0.9)" },
        },
        "pulse-ring": {
          "0%": { transform: "scale(0.33)" },
          "80%": { opacity: 0 },
          "100%": { opacity: 0 },
        },
        fadeIn: {
          "0%": {
            opacity: 0,
            transform: "translateY(20px)",
          },
          "100%": {
            opacity: 1,
            transform: "translateY(0)",
          },
        },
        slideUp: {
          from: { transform: "translateY(100%)", opacity: "1" },
          to: { transform: "translateY(0)", opacity: "1" },
        },
        appear: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
      },
      animation: {
        "pulse-dot":
          "pulse-dot 2s cubic-bezier(.455, 0.03, 0.515, 0.955) -0.4s infinite",
        "pulse-ring":
          "pulse-ring 2s cubic-bezier(0.215, 0.61, 0.355, 1) infinite",
        fadeIn: "fadeIn 0.5s ease-in-out",
        fadeInText: "fadeIn 0.5s ease-in-out 2.5s forwards",
        fadeInText1: "fadeIn 0.5s ease-in-out 2.6s forwards",
        fadeInText2: "fadeIn 0.5s ease-in-out 2.7s forwards",
        fadeInText3: "fadeIn 0.5s ease-in-out 2.8s forwards",
        fadeInText4: "fadeIn 0.5s ease-in-out 2.9s forwards",
        fadeInText5: "fadeIn 0.5s ease-in-out 3s forwards",
        fadeInText6: "fadeIn 0.5s ease-in-out 3.1s forwards",
        fadeInText7: "fadeIn 0.5s ease-in-out 3.2s forwards",
        fadeInText8: "fadeIn 0.5s ease-in-out 3.3s forwards",
        fadeInText9: "fadeIn 0.5s ease-in-out 3.4s forwards",
        fadeInText10: "fadeIn 0.5s ease-in-out 3.5s forwards",
        fadeInText11: "fadeIn 0.5s ease-in-out 3.6s forwards",
        fadeInText12: "fadeIn 0.5s ease-in-out 3.7s forwards",
        fadeInText13: "fadeIn 0.5s ease-in-out 3.8s forwards",
        fadeInText14: "fadeIn 0.5s ease-in-out 3.9s forwards",
        fadeInText15: "fadeIn 0.5s ease-in-out 4s forwards",
        fadeInText16: "fadeIn 0.5s ease-in-out 4.1s forwards",
        fadeInText17: "fadeIn 0.5s ease-in-out 4.2s forwards",
        fadeInText18: "fadeIn 0.5s ease-in-out 4.3s forwards",
        fadeInText19: "fadeIn 0.5s ease-in-out 4.4s forwards",
        fadeInText20: "fadeIn 0.5s ease-in-out 4.5s forwards",
        fadeInText21: "fadeIn 0.5s ease-in-out 4.6s forwards",
        fadeInText22: "fadeIn 0.5s ease-in-out 4.7s forwards",
        fadeInText23: "fadeIn 0.5s ease-in-out 4.8s forwards",
        fadeInText24: "fadeIn 0.5s ease-in-out 4.9s forwards",
        // Fade titre nav
        fadeInTitle1: "fadeIn 0.8s ease-in-out 0.8s forwards",
        fadeInTitle2: "fadeIn 0.7s ease-in-out 1s forwards",
        fadeInTitle3: "fadeIn 0.7s ease-in-out 1.1s forwards",
        fadeInTitle4: "fadeIn 0.7s ease-in-out 1.2s forwards",
        fadeInTitle5: "fadeIn 0.7s ease-in-out 1.3s forwards",
        fadeInTitle6: "fadeIn 0.7s ease-in-out 1.4s forwards",
        fadeInTitle7: "fadeIn 0.7s ease-in-out 1.5s forwards",
        appearsTitle1: "appear 0.3s ease-in-out 0.8s forwards",
        appearsTitle2: "appear 0.3s ease-in-out 1s forwards",
        appearsTitle3: "appear 0.3s ease-in-out 1.1s forwards",
        appearsTitle4: "appear 0.3s ease-in-out 1.2s forwards",
        appearsTitle5: "appear 0.3s ease-in-out 1.3s forwards",
        appearsTitle6: "appear 0.3s ease-in-out 1.4s forwards",
        appearsTitle7: "appear 0.3s ease-in-out 1.5s forwards",
        //
        appears: "appear 0.8s ease-in-out forwards",
        appearsAzra: "appear 0.3s ease-in-out 1.2s forwards",
        appears1: "appear 0.3s ease-in-out 1.6s forwards",
        appears2: "appear 0.3s ease-in-out 1.9s forwards",
        appears3: "appear 0.3s ease-in-out 2.3s forwards",
        appears4: "appear 0.3s ease-in-out 2.5s forwards",
        appears5: "appear 0.3s ease-in-out 2.6s forwards",
        appears6: "appear 0.3s ease-in-out 2.7s forwards",
        appears7: "appear 0.3s ease-in-out 2.8s forwards",
        appears8: "appear 0.3s ease-in-out 2.9s forwards",
        appears9: "appear 0.3s ease-in-out 3s forwards",
        appears10: "appear 0.3s ease-in-out 3.1s forwards",
        appears11: "appear 0.3s ease-in-out 3.2s forwards",
        appears12: "appear 0.3s ease-in-out 3.3s forwards",
        appears13: "appear 0.3s ease-in-out 3.4s forwards",
        appears14: "appear 0.3s ease-in-out 3.5s forwards",
        appears15: "appear 0.3s ease-in-out 3.6s forwards",
        appears16: "appear 0.3s ease-in-out 3.7s forwards",
        appears17: "appear 0.3s ease-in-out 3.8s forwards",
        appears18: "appear 0.3s ease-in-out 3.9s forwards",
        appears19: "appear 0.3s ease-in-out 4s forwards",
        appears20: "appear 0.3s ease-in-out 4.1s forwards",
        appears21: "appear 0.3s ease-in-out 4.2s forwards",
        appears22: "appear 0.3s ease-in-out 4.3s forwards",
        appears23: "appear 0.3s ease-in-out 4.4s forwards",
        appears24: "appear 0.3s ease-in-out 4.5s forwards",
        appears25: "appear 0.3s ease-in-out 4.6s forwards",
        slideUp1: " slideUp 1s cubic-bezier(0.45, 0.64, 0.12, 1)0s both",
        slideUp2: " slideUp 0.8s cubic-bezier(0.45, 0.64, 0.12, 1)0.3s both",
        slideUp3: " slideUp 0.7s cubic-bezier(0.45, 0.64, 0.12, 1)0.6s both",
      },
    },
  },
  plugins: [require("tailwindcss-animatecss")],
};
